// Code generated by protoc-gen-go. DO NOT EDIT.
// source: com.proto

/*
Package com is a generated protocol buffer package.

It is generated from these files:
	com.proto

It has these top-level messages:
	PingRequest
	PongResponse
	RandomMsgRequest
	RandomMsgResponse
*/
package com

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PongResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *PongResponse) Reset()                    { *m = PongResponse{} }
func (m *PongResponse) String() string            { return proto.CompactTextString(m) }
func (*PongResponse) ProtoMessage()               {}
func (*PongResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PongResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RandomMsgRequest struct {
}

func (m *RandomMsgRequest) Reset()                    { *m = RandomMsgRequest{} }
func (m *RandomMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*RandomMsgRequest) ProtoMessage()               {}
func (*RandomMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RandomMsgResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *RandomMsgResponse) Reset()                    { *m = RandomMsgResponse{} }
func (m *RandomMsgResponse) String() string            { return proto.CompactTextString(m) }
func (*RandomMsgResponse) ProtoMessage()               {}
func (*RandomMsgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RandomMsgResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "com.PingRequest")
	proto.RegisterType((*PongResponse)(nil), "com.PongResponse")
	proto.RegisterType((*RandomMsgRequest)(nil), "com.RandomMsgRequest")
	proto.RegisterType((*RandomMsgResponse)(nil), "com.RandomMsgResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Pinger service

type PingerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type pingerClient struct {
	cc *grpc.ClientConn
}

func NewPingerClient(cc *grpc.ClientConn) PingerClient {
	return &pingerClient{cc}
}

func (c *pingerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := grpc.Invoke(ctx, "/com.Pinger/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pinger service

type PingerServer interface {
	Ping(context.Context, *PingRequest) (*PongResponse, error)
}

func RegisterPingerServer(s *grpc.Server, srv PingerServer) {
	s.RegisterService(&_Pinger_serviceDesc, srv)
}

func _Pinger_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.Pinger/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pinger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.Pinger",
	HandlerType: (*PingerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Pinger_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com.proto",
}

// Client API for RandomMsg service

type RandomMsgClient interface {
	GetRandomMsg(ctx context.Context, in *RandomMsgRequest, opts ...grpc.CallOption) (*RandomMsgResponse, error)
}

type randomMsgClient struct {
	cc *grpc.ClientConn
}

func NewRandomMsgClient(cc *grpc.ClientConn) RandomMsgClient {
	return &randomMsgClient{cc}
}

func (c *randomMsgClient) GetRandomMsg(ctx context.Context, in *RandomMsgRequest, opts ...grpc.CallOption) (*RandomMsgResponse, error) {
	out := new(RandomMsgResponse)
	err := grpc.Invoke(ctx, "/com.RandomMsg/GetRandomMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RandomMsg service

type RandomMsgServer interface {
	GetRandomMsg(context.Context, *RandomMsgRequest) (*RandomMsgResponse, error)
}

func RegisterRandomMsgServer(s *grpc.Server, srv RandomMsgServer) {
	s.RegisterService(&_RandomMsg_serviceDesc, srv)
}

func _RandomMsg_GetRandomMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomMsgServer).GetRandomMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.RandomMsg/GetRandomMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomMsgServer).GetRandomMsg(ctx, req.(*RandomMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RandomMsg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.RandomMsg",
	HandlerType: (*RandomMsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomMsg",
			Handler:    _RandomMsg_GetRandomMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com.proto",
}

func init() { proto.RegisterFile("com.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xce, 0xcf, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0xce, 0xcf, 0x55, 0x92, 0xe7, 0xe2, 0x0e, 0xc8,
	0xcc, 0x4b, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x2d, 0x4e,
	0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x14, 0xb8, 0x78, 0x02, 0xf2, 0x41,
	0x0a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xb1, 0xa8, 0x10, 0xe2, 0x12, 0x08, 0x4a, 0xcc, 0x4b,
	0xc9, 0xcf, 0xf5, 0x2d, 0x86, 0x99, 0xa3, 0xa4, 0xca, 0x25, 0x88, 0x24, 0x86, 0x4b, 0xab, 0x91,
	0x39, 0x17, 0x1b, 0xc8, 0xf6, 0xd4, 0x22, 0x21, 0x5d, 0x2e, 0x16, 0x10, 0x4b, 0x48, 0x40, 0x0f,
	0xe4, 0x40, 0x24, 0x27, 0x49, 0x09, 0x42, 0x44, 0x90, 0xdc, 0xa0, 0xc4, 0x60, 0xe4, 0xc3, 0xc5,
	0x09, 0x37, 0x5f, 0xc8, 0x9e, 0x8b, 0xc7, 0x3d, 0xb5, 0x04, 0xc1, 0x17, 0x05, 0xeb, 0x40, 0x77,
	0x93, 0x94, 0x18, 0xba, 0x30, 0xcc, 0xb4, 0x24, 0x36, 0x70, 0x80, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x85, 0x41, 0xbd, 0xb6, 0x1d, 0x01, 0x00, 0x00,
}
